document.write("					</td>");
document.write("					<td valign=top><img src=\"start.gif\"></td>");
document.write("				</tr>");
document.write("			</table>");
document.write("		</td>");
document.write("	</tr>");
document.write("</table><br><br>");
document.write("<table width=\"100%\" cellpadding=0 cellspacing=0 border=0>");
document.write("	<tr>");
document.write("		<td valign=top align=center style=\"font-size:60%; color:#A0A0A0\">");
document.write("			<hr size=1 color=\"#C0C0C0\">");
document.write("			Copyright &copy; 2002, NZ Software");
document.write("		</td>");
document.write("	</tr>");
document.write("</table>");
document.write("</body></html>");