document.write("<html><head><title>Hex Color Finder Help - " + pagename + "</title>");
document.write("<link rel=\"StyleSheet\" href=\"help.css\"></head>");
document.write("<body bgcolor=\"#ffffff\" text=\"#000000\" link=\"#0070B0\" vlink=\"#0070B0\" alink=\"#000000\" leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">");
document.write("<table width=\"100%\" cellpadding=0 cellspacing=0 border=0>");
document.write("	<tr>");
document.write("		<td valign=top background=\"topbg.gif\"><img src=\"top.gif\"></td>");
document.write("		<td valign=middle align=right class=\"headertext\" background=\"topbg.gif\" nowrap>" + pagename + "<img src=\"blank.gif\" width=10></td>");
document.write("	</tr>");
document.write("</table>");
document.write("<table width=\"100%\" cellpadding=15 cellspacing=0 border=0>");
document.write("	<tr>");
document.write("		<td valign=top>");
document.write("			<table width=100% cellpadding=0 cellspacing=0 border=0>");
document.write("				<tr>");
document.write("					<td valign=top width=100%>");
document.write("						<h1>" + pagename + "</h1><br>");
